### ISSUE TITLE
`socket2::SockRef::from()` doesn't work with tokio sockets anymore

### ISSUE THREAD

**Issue by gregoire-mullvad** [rust-lang/socket2#402]
With socket2 0.5 it is no longer possible to use `SockRef::from()` with a tokio socket (using tokio 1.25.0.)

The following code works with socket2 0.4:
```rs
#[tokio::main]
async fn main() {
    let tokio_socket = tokio::net::TcpSocket::new_v4().unwrap();
    let socket2_socket = socket2::SockRef::from(&tokio_socket);
}
```

But breaks with 0.5:

```
error[E0277]: the trait bound `TcpSocket: AsFd` is not satisfied
 --> src/main.rs:4:49
  |
4 |     let socket2_socket = socket2::SockRef::from(&tokio_socket);
  |                          ---------------------- ^^^^^^^^^^^^^ the trait `AsFd` is not implemented for `TcpSocket`
  |                          |
  |                          required by a bound introduced by this call
  |
  = help: the following other types implement trait `AsFd`:
            &T
            &mut T
            Arc<T>
            BorrowedFd<'_>
            Box<T>
            OwnedFd
            PidFd
            Socket
          and 20 others
  = note: required for `SockRef<'_>` to implement `From<&TcpSocket>`

For more information about this error, try `rustc --explain E0277`.
```

**Comment by Thomasdezeeuw** [comment]
As stated in the changed: https://github.com/rust-lang/socket2/blob/master/CHANGELOG.md#changed:
> `From<S>` is now implemented using the I/O traits `AsFd` and `AsSocket`

We added some safety around `SockRef` so now it only accepts know good fd/sockets. Tokio's types should implement [`AsFd`](https://doc.rust-lang.org/stable/std/os/fd/trait.AsFd.html) and [`AsSocket`](https://doc.rust-lang.org/stable/std/os/windows/io/trait.AsSocket.html).

**Comment by Thomasdezeeuw** [comment]
Also see https://github.com/tokio-rs/tokio/pull/5514 for the implementations added to Tokio.
